### ISSUE TITLE
[[uuid|id]] in checkbox

### ISSUE THREAD

**Issue by linuxcaffe** [teranex/vimwiki-tasks#14]
I feel quite strongly that while ID is a transient, and not a good programatic reference (like UUID) but it IS the user-handle for all tasks. If a user wants to take an immediate action with tw or an extension, it will almost always be using the ID(s) as reference.

So it _has_ to be visible, and to me the most economical, obvious spot is in the checkbox, but I would otherwise treat this checkbox like usual. Now that you have figured out how to conceal the UUID, maybe the checkbox could act like a link, with uuid as target, and ID as the displayed value?

When a task is completed, and it loses it's ID, that should change to [[uuid|X]]

**Comment by teranex** [comment]
I was considering to add a configuration option to optionally include the ID in the line, however it really complicates things. Basically it would mean that, when a task is marked as finished in VW and the file is saved all the tasks in the file would have to be rewritten because the ID might have changed. And even without writing the file, if you close a task from the commandline and run a task report on the CLI the ID's might be out-of-sync in VW. It think this could quickly lead to using wrong ID's on the commandline, copied from an out-of-sync VW file.
I am considering however to add `:DisplayTaskID` and `:CopyTaskID` commands to display the Task ID and copy it to the clipboard. Running the command would load the correct ID for the task on the current cursorline, making sure that it is the correct up-to-date ID at that moment.

I really don't like the idea of adding the ID inside the checkbox at the beginning of the tag line as that would break the vimwiki functionality which expects [ ], [.] [o] or [X] so that should be left untouched.

**Comment by linuxcaffe** [comment]
Well I wouldn't want to break anything :) I imagine those marks for todos coexisting happily, and they don't have an analog for tw tasks, so let 'em live!
When the tasks are completed the IDs _will have_ changed, and my suggestion there was to replace [[uuid|id]] with [[uuid|X]] which has the best of several worlds, where it maintains the uuid link and conforms to the "done" condition of todos,, 

imho, without IDs prominent somehow, some substantial amount of functionality is disabled. You can't look at a VW task and decide to do something spontaneous to it with one of the many other tools at your disposal, like the command-line..

**Comment by teranex** [comment]
I have implemented the `:DisplayTaskID` and `:CopyTaskID` commands to display and copy the current ID for the task under the cursor.

**Comment by teranex** [comment]
Another idea I just got after reading your latest remark about doing something spontaneous:
I could add a `:TaskCmd` command which would basically accept any number of arguments and execute them as 'task <id of currently focused task> <arguments>'. Then it would be possible to put the cursor on a task in VW (say with ID 14) and execute `:TaskCmd done` which would translate to `task 14 done`. With such a command available you wouldn't even need to know the ID.
I'll have to think a bit more about this..

**Comment by linuxcaffe** [comment]
cool!

**Comment by teranex** [comment]
I also added the `:CopyTaskUUID` command (and `:DisplayTaskUUID` for the sake of completeness). Since taskwarrior is smart enough to be able to uniquely identify a task using it's ID and it's UUID you can as well just copy the UUID and use that on the commandline.

**Comment by teranex** [comment]
I have also added the `:TaskCmd` command. Now you can do for example:

```
:TaskCmd mod /foo/bar/ +tag
:TaskCmd done
```

And it will execute the correct `task` command with the uuid for the task under the cursor. It will also reload the line in VW to make sure it is updated.
