### ISSUE TITLE
check last modification-time of task before updating it when saving file.

### ISSUE THREAD

**Issue by linuxcaffe** [teranex/vimwiki-tasks#16]
Maybe a very early step should be to see if any changes have occurred to pending.data since "the last time", because _that_ could have implications for syncing confusion.

**Comment by teranex** [comment]
Simply checking the modification time for pending.data does not really give very useful information. However, since TW stored the last modification timestamp for each task, that might be useful. When opening the vimwiki file I could store the current time and when saving, compare it with the last modification time of each individual task. If the modification time is newer,  then I could ask what to do with that specific task.

**Comment by teranex** [comment]
I implemented checks for each individual task. When saving a file in Vimwiki the last_modified date/time of the taskwarrior will be checked. If the task was modified in taskwarrior after the file was opened in vimwiki, vw-tasks will ask you what it should do with the task.
