### ISSUE TITLE
vimwiki-tasks and TODOs are too similar

### ISSUE THREAD

**Issue by linuxcaffe** [teranex/vimwiki-tasks#22]
When you said tasks and TODOs could co-exist, you weren't kidding!

A vimwiki todo (not connected to tw) can be inserted within a TaskList and it looks identical, even using the same syntax highlighting for +tags (even if a tag in a todo doesn't do anything) and the only way to tell that it's not a tw task is to move the cursor over it, and notice how UUID does _not_ pop up.

Coexisting is good, but there should be some clear visual clue differentiating the two types.

**Comment by teranex** [comment]
Tasks which are in TW will now display a 'T' at the end of the line (where the GUID actually is). This makes it possible to differentiate between tasks only in vimwiki and tasks which are also in TW. I would have liked to display '#tw' instead of simply 'T', but apparently Vim only allows a single character as a visibile replacement for concealed text.
